### ISSUE TITLE
The IP address and/or port specified is invalid, please change it.  [Errno 111] Connection refused

### ISSUE THREAD

**Issue by XingpingGY** [Wanchai290/tmita-optical-cardyomyocyte-analysis#14]
I followed with your introduction and it went really well. The raspberry pi has been connecting with the computer running the tracking software. When I ping under the terminal it looked good as below.
```powershell
PING 192.168.0.10 (192.168.0.10) 56(84) bytes of data.
64 bytes from 192.168.0.10: icmp_seq=1 ttl=64 time=0.156 ms
64 bytes from 192.168.0.10: icmp_seq=2 ttl=64 time=0.240 ms
64 bytes from 192.168.0.10: icmp_seq=3 ttl=64 time=0.359 ms
64 bytes from 192.168.0.10: icmp_seq=4 ttl=64 time=0.349 ms
64 bytes from 192.168.0.10: icmp_seq=5 ttl=64 time=0.300 ms
64 bytes from 192.168.0.10: icmp_seq=6 ttl=64 time=0.263 ms
64 bytes from 192.168.0.10: icmp_seq=7 ttl=64 time=0.263 ms
64 bytes from 192.168.0.10: icmp_seq=8 ttl=64 time=0.358 ms
^C
--- 192.168.0.10 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7156ms
rtt min/avg/max/mdev = 0.156/0.286/0.359/0.065 ms
``` 
However when I clicked from live server it was said  The IP address and/or port specified is invalid, please change it.  [Errno 111] Connection refused. It seems that the custom_raspberrypi_headless.py did not work as wished. When I ran it via terminal there is no any response to input the IP address.

**Comment by Wanchai290** [comment]
At the moment I do not have access to a RaspberryPi to perform some tests on my own, so I will have to rely on you for testing.
I'm guessing it either comes from the text input which might've been badly converted, or that it could come from the port.

After going through the code and tutorial again, I realized I missed some critical parts that were obvious for me but not that obvious for others. This will be fixed in the next release. In the meantime, proceed by doing these steps :

1. At the end of the file `custom_raspberrypi_headless.py`, add the following lines :
```python3
if __name__ == '__main'__:
	main()
```
2. On the RaspberryPi, open a terminal in the folder containing this file and run it with the following command
```bash
python3 custom_raspberrypi_headless.py
```
3. Follow the instructions of the script when prompted to.
4. The RaspberryPi should now listen for connections on the IP address you've configured and specified when running the script

Side note : I realized I put the label 'IP Address' to both inputs in the tracking software, sorry for this. The first box is for the IP address, and the second one is for port.

Please notify me if something goes wrong, I will try to find a RaspberryPi to test it on my own.

**Comment by Wanchai290** [comment]
I just reviewed the file and it seems there is a lot of stuff missing for it to work properly. I don't really know where I messed up my file management with Git, this is completely my fault. I will be reworking this and it should be *theoretically* functional in the next release (I still have to find a RaspberryPi)

**Comment by Wanchai290** [comment]
After some thought on my end, I recall that the RaspberryPi is currently on Python 3.9 which does not accept multiple type hints for a variable using a pipe '|' (or for a function return). In short, Python 3.9 forbids this :
```py
def f(x) -> int | str:  # "int | str" crashes because the | operator couldn't be used for multiple types in Python 3.
    new_var: int = 2  # But type hints still exist
```

#21 should fix this in the next release

**Comment by XingpingGY** [comment]
Thank you so much for your prompt reply!

**Comment by XingpingGY** [comment]
Now I add
```python
if __name__ == '__main'__:
    main()
``` and the program shows such error. 
```shell
..., in main
     frames_queue: Queue[tuple[int, ndarray]] = Queue()
NameError: name 'Queue' is not defined
``` 
It seems that fames_queue function is not working well.

**Comment by XingpingGY** [comment]
Since the raspberry pi is able to run the open cv library, why do we to build the connection between raspberry pi and laptop?Could we directly combine the tracking software with the microscope.py file and run it on raspberry pi?

**Comment by XingpingGY** [comment]
Since the raspberry pi is able to run the open cv library, why do we to build the connection between raspberry pi and laptop?Could we directly combine the tracking software with the microscope.py file and run it on raspberry pi?

**Comment by Wanchai290** [comment]
This is a possibility, but the main factor  is the RaspberryPi computing power. I didn't know whether it would be able to withstand both the capturing of the camera and the tracking software itself. 

Instead of coding an extension particularly for the RaspberryPi, I went with a more generic approach to allow any other possible device to perform as a video feed provider. The fun fact about the latter is that you could technically send a video feed over the Internet with the approach I've implemented, but it wasn't the primary goal.

I had news bugs come up in the latest release so it should come out soon, by the end of the week probably. I fell sick not long ago so I didn't have time to work on the project.

In the meantime, you could extend the `AbstractFrameProvider` class for an implementation specific to the lab. You will also need to create a QAction in the Qt menus that I've configured for that.

**Comment by XingpingGY** [comment]
Yes you are right. I just saw the tracking program from OpenCV realized by raspberri pi 4. This way you do is more trackable. I will look into your code and see if there is anything I can do to extend the class `AbstractFrameProvider`.

**Comment by Wanchai290** [comment]
I've deployed the latest release on this repository, you can check it [here](https://github.com/Wanchai290/tmita-optical-cardyomyocyte-analysis/releases). The custom RaspberryPi script has been modified, could you please try to upload this one on the RaspberryPi and launch it using the same tutorial as before ? I'll stay available if any other problem arises

**Comment by XingpingGY** [comment]
With the 1.1 version just downloaded I ran with this error:
```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/Main.py", line 53, in <module>
    worker.run()
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/Main.py", line 42, in run
    self._live_feed_wrapper.start()
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/logic/video/LiveFeedWrapper.py", line 21, in start
    self._feed.start()
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/logic/video/DummyVideoFeed.py", line 52, in start
    self._load_static_frames()
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/logic/video/DummyVideoFeed.py", line 27, in _load_static_frames
    with os.scandir(os.path.abspath('../../assets/dummy_feed_frames/')) as directory:
FileNotFoundError: [Errno 2] No such file or directory: '/home/biotft/assets/dummy_feed_frames'
``` 
It seems that in the file `DummyVideoFeed.py` this code `with os.scandir(os.path.abspath('../../assets/dummy_feed_frames/')) as directory:` cannot offer the right path in my case.
Now I change it as `directory_path = os.path.abspath('../../Downloads/tmita-optical-cardyomyocyte-analysis-1.1/assets/dummy_feed_frames/')
        if os.path.exists(directory_path):` and it works.
        I will test its communication part.

**Comment by XingpingGY** [comment]
Sorry there are still some missing parts in `comm_protocol` files especially in `FrameTCPServer.py` this file. It seems that this class has different attributes defined and when it is used there are always errors about that. I will test it further, I hope you can revise it from your end as well.

**Comment by Wanchai290** [comment]
Sorry for the errors you went through, about the directory problem I will fix this ASAP, it seemed correct on my end but I keep messing up this kind of stuff.

Thank you very much for forking the repo properly and proposing a PR ! There is probably not much I can do do test it and all of it seems correct, so I will merge it when I get the time.

> Now it seems we can build stable connection now! But when I got the live streaming image of raspberry pi the error occurs: `picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources`. Do you have any clues Wan chai?

After some quick googling, this happens when the camera is used by another process (see this [link](https://github.com/waveform80/picamera/issues/488)).  Maybe when the custom script gets killed or halted by a SIGKILL signal (the typical CTRL-C), the camera is not released properly in the software. I will have a look into it to add a signal handler in the script that will repair this. In the meantime, force-closing the program then waiting a bit might do the job. I will write the signal handler today and you should have it ready by tomorrow (Japanese time).  
Always ensure the progrma is only launched once, and that no other program is using the camera !

**Comment by XingpingGY** [comment]
Thank you for your time! I googled this problem and I was told the same thing but I did not how to fix it so far......I will test it as soon as possible and make sure no other program is using the camera when doing the test.

**Comment by Wanchai290** [comment]
The new version release (v1.1.1) that contains your fixes and proper release of the camera should fix the last problems that you've had in the last week. Working this way is fairly new to me so excuse me if I'm not very good at it. If you need, we can schedule a video meeting to sort things out if necessary !

**Comment by XingpingGY** [comment]
Thanks a lot. This task is new to me as well and thanks for your contribution of the tracking software and communication protocol. I will test the latest version(v1.1.1) tomorrow if there is still some problem I do not know. Maybe we can arrange a video meeting for it. Thank you in advance!
