### ISSUE TITLE
Trying to replace the TCP with zmq lib

### ISSUE THREAD

**Issue by XingpingGY** [Wanchai290/tmita-optical-cardyomyocyte-analysis#36]
I rewrite the `FramesFromDistantServer` as this:
```python
from threading import Event
import zmq
import numpy as np

class FramesFromDistantServer(AbstractFrameProvider):
    def __init__(self, ip_address: str, port: int, global_halt: Event, max_frames_in_queue: int = 30):
        super().__init__(global_halt, False, max_frames_in_queue)
        self._zmq_context = zmq.Context()
        self._zmq_socket = self._zmq_context.socket(zmq.SUB)
        self._zmq_socket.connect(f"tcp://{ip_address}:{port}")
        self._zmq_socket.setsockopt_string(zmq.SUBSCRIBE, "")  # Subscribe to all topics

    def start(self):
        frame_num = 0
        while not self._global_halt.is_set():
            frame_data = self._zmq_socket.recv()  # Receive frame data via ZeroMQ
            width, height, img_data = extract_resolution_and_data(frame_data)
            img_arr = np.frombuffer(img_data, dtype=np.uint8).reshape((height, width, 3))
            self._frames_queue.put((frame_num, img_arr))
            frame_num += 1

    def stop(self):
        self._zmq_socket.close()
        self._zmq_context.term()

def extract_resolution_and_data(message):
    msg_parts = message.split(b' ', 2)
    print(f"Received message parts: {msg_parts}")  # Print the received message parts for debugging
    try:
        width = int(msg_parts[0])
        height = int(msg_parts[1])
        img_data = msg_parts[2]
        print(f"Extracted resolution: width={width}, height={height}")
        return width, height, img_data
    except ValueError as e:
        print(f"Error extracting resolution: {e}")
        return 0, 0, b''

``` 
Though it seems the laptop can receive the message from server, the camera's image did not come up on the software.
In command it was said:
```shell
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\^CTraceback (most recent call last):
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/qt_gui/top_menu_bar/video/SelectFramesFromServerAction.py", line 19, in _new_live_dialog
    self._live_feed.change_feed(feed)
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/logic/video/LiveFeedWrapper.py", line 41, in change_feed
    self._feed.start()
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/logic/video/FramesFromDistantServer.py", line 18, in start
    width, height, img_data = extract_resolution_and_data(frame_data)
  File "/home/biotft/Downloads/tmita-optical-cardyomyocyte-analysis-1.1/src/pattern_tracking/logic/video/FramesFromDistantServer.py", line 30, in extract_resolution_and_data
    print(f'Received message parts: {msg_parts}')
KeyboardInterrupt

``` 
What files else should I modify as well?
Thanks in advance.

**Comment by Wanchai290** [comment]
Sorry for the late answer,

In theory, the code you have written should suffice for the main window to start displaying frames. The main loop performs a blocking call to the frame provider class to wait for an image to display. In other words, nothing is displayed because we are waiting for an image.

I suggest using the `Packet.py` structure already defined, and instead of writing an image as bytes to the ZMQ socket, send the content of `packet.serialize()` over the socket. It requires extra lines to fully read the buffer, and eliminate the noise in the communication link, but should ensure more stability (obviously, it won't be as fast, but in theory the impact should be minimal)

I've had trouble with work these past days so I cannot find the time to work on it. I will try to do this in my free time.

**Comment by XingpingGY** [comment]
Thank you very much for your effort!

**Comment by Wanchai290** [comment]
after some tinkering with ZMQ, I found out you need to launch the subscriber **before** the publisher so that it correctly fetches the messages. there's still some work to do on the UI end, this should be ready before Wednesday. If you want, you can always take the branch out and propose a PR that takes care of the mentioned items in the PR. But I can also do it if you'd like, still a pleasure to work on it.

**Comment by XingpingGY** [comment]
I am really appreciated if you could it Wanchai. This week I am kind of busy due to cells and the preparation for the conference. Thank you very much in advance.
